add demos for cryptographic functions with and without
wolfSSL/wolfHSM-examples pull request #13
Opened 2024-07-22 02:33 UTC by jpbland1

imported keys

2024-07-22 20:35 UTC, bigbrett requested changes
Awesome, thanks so much for this @jpbland1. Just a few changes/cleanups and things to make it clearer for the reader

2024-07-22 20:35 UTC, bigbrett commented on demo/client/wh_demo_client_crypto.c
> +    char pubKeyFileTwo[] = "../../../demo/certs/ecc-public-two.raw";
same comment as above re: Alice and Bob

2024-07-22 20:35 UTC, bigbrett commented on demo/client/wh_demo_client_crypto.c
> +int wh_DemoClient_CryptoAesGcmImport(whClientContext* clientContext)
I think it is slightly clearer to the reader if you cache the key first thing, then indicate the subsequent AES operations (including init) can happen at any point later, even after a power cycle, hence the "import". [See this keycache demo](https://github.com/wolfSSL/wolfHSM-examples/blob/62ebf7cbbd85951f5fbc58e209a72af2e467bac5/demo/client/wh_demo_client_keystore.c#L120). Maybe we just make the two identical, with the exception of using GCM in this one?

2024-07-22 20:35 UTC, bigbrett commented on demo/client/wh_demo_client_crypto.c
> +int wh_DemoClient_CryptoCmacImport(whClientContext* clientContext)
same comment re: order of operations - cache first, then write a comment indicating the significance of what we just did and that the remaining cmac operations can just refer to the ID

2024-07-22 20:35 UTC, bigbrett commented on demo/client/wh_demo_client_crypto.c
> +     * can be done as above */
```suggestion
    /* Verify the tag. Note that in order to use a cached key for 
     * CMAC verification, it is necessary to use the special wolfHSM 
     * client API function: wh_Client_AesCmacVerify() */
```

2024-07-22 20:35 UTC, bigbrett commented on demo/client/wh_demo_client_crypto.c
> +     * can be done as above */
Also, pedantic to us, but good for the user: we should do a separate one-shot example using the Client API, vs just mentioning it in the comment for the verify

2024-07-22 21:09 UTC, jpbland1 commented on demo/client/wh_demo_client_crypto.c
> +    char pubKeyFileTwo[] = "../../../demo/certs/curve25519-public-two.raw";
great idea

2024-07-22 21:10 UTC, jpbland1 commented on demo/client/wh_demo_client_crypto.c
> +    /* public from the first shared secret's perspective, actually private */
it's fine, just named from perspective one

2024-07-22 21:11 UTC, jpbland1 commented on demo/client/wh_demo_client_crypto.c
> +int wh_DemoClient_CryptoAesGcmImport(whClientContext* clientContext)
it's fine, the order ultimately doesn't matter so ordering it any way will convey this

2024-07-22 21:12 UTC, jpbland1 commented on demo/client/wh_demo_client_crypto.c
> +     * can be done as above */
I wanted to show the cached key doing operations both manually and with a helper function but I also wanted to make the comment with both functions included so they understand that oneshot generate also has it's own special function

2024-07-22 21:23 UTC, bigbrett requested changes
missed a typo and think we should create a one shot CMAC demo function, since it is a special case and we should highlight it

2024-07-22 21:23 UTC, bigbrett commented on demo/client/wh_demo_client_crypto.c
> +    /* initialize rng to make the cruve25519 keys */
@jpbland1 Somehow I didn't notice the double typo the first time XD
```suggestion
    /* initialize rng to make the curve25519 keys */
```

2024-07-22 21:23 UTC, bigbrett commented on demo/client/wh_demo_client_crypto.c
> +     * can be done as above */
I understand, I'm saying go one step further and add a oneshot generate example too, as opposed to just leaving the note about using the client API for oneshots in the comment. Harder to miss. That way we are explicitly demonstrating the correct way to do a oneshot CMAC in the demo code. Just create a `whDemoClient_CryptoCmacOneshotImport()` with the same input data.

2024-07-22 22:18 UTC, jpbland1 commented
gotcha, added the oneshot example

2024-07-23 14:26 UTC, bigbrett approved these changes

2024-07-23 14:26 UTC, merged