Made example more comprehensive
wolfSSL/wolfHSM-examples pull request #9
Opened 2024-05-30 17:15 UTC by jackctj117

Just added some better print outs for connections between server and client.

2024-05-30 20:53 UTC, bigbrett requested changes

2024-05-30 20:53 UTC, bigbrett commented on posix/tcp/wh_client_tcp/wh_client_tcp.c
> +                continue;
we should just remove this if statement if it no longer does anything, no point in keeping it around. Though it would be helpful to keep a printout that displays the error code that caused the failure. Why did you want to remove this?

2024-05-30 21:15 UTC, jackctj117 commented on posix/tcp/wh_client_tcp/wh_client_tcp.c
> +                continue;
Or would you rather I get rid of the statement?

2024-05-30 21:46 UTC, bigbrett commented on posix/tcp/wh_client_tcp/wh_client_tcp.c
> +                continue;
Well, that output would only be shown if there was a real error, so I'd keep it in. Maybe just make the printout more clear, since I think `tx_req` and `tx_req_len` wouldn't be populated on error anyway. Something like `printf("wh_Client_EchoRequest failed with ret=%d\n", ret);`

2024-05-31 19:27 UTC, bigbrett requested changes

2024-05-31 20:19 UTC, jackctj117 commented on posix/tcp/wh_client_tcp/wh_client_tcp.c
> +                }
I thought `!= WH_ERROR_NOTREADY` meant it was a pass, before I changed the contents of that case what ever is in it prints out. If that case is a fail then it seems the example has more issues than originally thought.

2024-06-03 15:16 UTC, bigbrett commented on posix/tcp/wh_client_tcp/wh_client_tcp.c
> +                }
No, the example is correct as it was written (at least this part of it), your assumption about how it works is incorrect. `ret != WH_ERROR_NOTREADY` doesn't mean it is a pass, the function could very well return a fatal error here. But if it returns `0` then it is success. Note the conditions of the `do while` loop. The original example printed the return value and the contents of the buffer on success AND if there was an error code `!= WH_ERROR_NOTREADY`. You just changed that to say "success", when in reality a fatal error code could have been returned.

2024-06-03 15:17 UTC, jackctj117 commented on posix/tcp/wh_client_tcp/wh_client_tcp.c
> +                }
Oh I see, I will fix this. Thank you for the clarification!

2024-06-03 16:52 UTC, jackctj117 commented on posix/tcp/wh_client_tcp/wh_client_tcp.c
> +                }
I believe I addressed the case appropriately now.

2024-06-03 17:58 UTC, bigbrett approved these changes

2024-06-03 17:58 UTC, merged